version: "3.8"

services:
  frontend:
    build: mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern

  backend:
    build: mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern

volumes:
  mongo-data:
    driver: local

networks:
  mern:
    driver: bridge

